name: A workflow for my Hello World file
on: push
jobs:
  npm:
    strategy:
      matrix:
        node-version: [15.x]
    name: Node
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install

  build-and-push:
    name: build and push image
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master #Clona el repo 
    - name: build and push to docker
      uses: docker/build-push-action@v2 #build and push to docker hub
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: dfavaedrans/cicd-sot-2022
        push: true
        #tag_with_ref: true
        #tag_with_sha: true
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}     